### PR TITLE
Css colors

### PR DESCRIPTION
**Pull request by MahtaMirzaei**
Related: #3 
About this issue:
Would you rather I used the same method for applying stylesheets to each of the "Hello World"s? I mean something like using an id for each one of them or using a paragraph tag for them all, not headers.

This time(last commit) I used vs code for coding and did add lines at the end of each file, but it seems like there are no empty lines at the end of files. Why did this happen?

### CODE REVIEW

**Comment by mkermani144** [comment]
Before answering your questions, I prefer you fix your code first. The changes of the other branch are present in this PR. Please consider checking your changes before submitting a PR.

**Comment by MahtaMirzaei** [comment]
> Before answering your questions, I prefer you fix your code first. The changes of the other branch are present in this PR. Please consider checking your changes before submitting a PR.

I honestly feel like I screwed up a little bit. Is it fixed now?

**Comment by mkermani144** [comment]
> > Before answering your questions, I prefer you fix your code first. The changes of the other branch are present in this PR. Please consider checking your changes before submitting a PR.
> 
> I honestly feel like I screwed up a little bit. Is it fixed now?

No. You can check the changes of the PR.  
These issues happen because of creating branches from branches other than `main`. When starting a new issue, ALWAYS checkout to `main` and create a branch from it.

**Comment by MahtaMirzaei** [comment]
> > I honestly feel like I screwed up a little bit. Is it fixed now?
> 
> No. You can check the changes of the PR. These issues happen because of creating branches from branches other than `main`. When starting working on a new issue, ALWAYS checkout to `main` first, and create a branch from it.

This makes sense. would you like me to delete this branch and start over, creating the new branch from the main branch?
Also by screwing up, I meant what happened with a simple issue and 17 comments below, Even though I did learn a lot more because of those comments.

**Comment by mkermani144** [comment]
@MahtaMirzaei Yes, you can close the PR.
And, it's ok to screw up. As you mentioned, the main point here is to learn, and learning by failing is the best method for learning something new in my opinion.

**Pull request closed without merging**
