### PR TITLE
dom manipulation on a new branch

### PR DESCRIPTION
**Pull request by MahtaMirzaei**
Closes: #54

### CODE REVIEW

**Review by mkermani144 — CHANGES_REQUESTED** [review]
There is something wrong in your code that prevents the 50% increase of the lower squares.

**Comment by MahtaMirzaei** [comment]
> There is something wrong in your code that prevents the 50% increase of the lower squares.

**Comment by mkermani144** [comment]
> > There is something wrong in your code that prevents the 50% increase of the lower squares.
> 
> I don't get it. it's functioning alright(for all the squares). are there any lines I must change? @mkermani144

I'm not sure about which lines need to be changed, but the size of the squares doesn't increase by 50%, while it's part of the issue.

**Comment by MahtaMirzaei** [comment]
> > > There is something wrong in your code that prevents the 50% increase of the lower squares.
> > 
> > I don't get it. it's functioning alright(for all the squares). are there any lines I must change? @mkermani144
> 
> I'm not sure about which lines need to be changed, but the size of the squares doesn't increase by 50%, while it's part of the issue.

That is really wierd cause I checked like twice, and the output is exactly like mr mrf's🥲

**Comment by MahtaMirzaei** [comment]
And the outputs are all decreased in size by 50%

**Comment by MahtaMirzaei** [comment]
Exept for the part in which we click on the button, there all of my f subtree's size is reduced by 50%, while mr mrf's increased by 50%

**Comment by mkermani144** [comment]
> Exept for the part in which we click on the button, there all of my f subtree's size is reduced by 50%, while mr mrf's increased by 50%

Then fix it. The issue asks for an increase, not a decrease.

**Comment by MahtaMirzaei** [comment]
> > Exept for the part in which we click on the button, there all of my f subtree's size is reduced by 50%, while mr mrf's increased by 50%
> 
> Then fix it. The issue asks for an increase, not a decrease.

done. I got it wrong before

**Review by mkermani144 — APPROVED** [review]

**Pull request merged**
